M48
; DRILL file KiCad 10.0.6 date 2026-09-27T01:16:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-27T01:16:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X128.76Y-60.49
X128.76Y-75.73
T2
X103.5Y-53.5
X103.5Y-84.5
X144.5Y-53.5
X144.5Y-84.5
M30
